2019-12-13 18:09:05 WARN  ConnectionUtil:23 - Unable to get connection to database
2019-12-13 18:11:58 WARN  ConnectionUtil:23 - Unable to get connection to database
2019-12-13 18:14:53 WARN  ConnectionUtil:23 - Unable to get connection to database
2019-12-13 18:17:24 WARN  ConnectionUtil:23 - Unable to get connection to database
2019-12-14 11:08:56 WARN  ConnectionUtil:23 - Unable to get connection to database
2019-12-14 11:18:31 WARN  ConnectionUtil:23 - Unable to get connection to database
2019-12-14 11:20:51 WARN  ConnectionUtil:23 - Unable to get connection to database
2019-12-14 11:21:13 WARN  ConnectionUtil:23 - Unable to get connection to database
2019-12-14 11:26:05 WARN  ConnectionUtil:23 - Unable to get connection to database
2019-12-14 11:29:00 WARN  ConnectionUtil:23 - Unable to get connection to database
2019-12-14 11:30:27 WARN  ConnectionUtil:76 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:74)
	at com.revature.repositories.EmployeeDAOImp.findById(EmployeeDAOImp.java:54)
	at com.revature.Driver.main(Driver.java:23)
2019-12-14 11:43:32 WARN  EmployeeDAOImp:80 - Unable to insert user.
org.postgresql.util.PSQLException: Can't use query methods that take a query string on a PreparedStatement.
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:95)
	at com.revature.repositories.EmployeeDAOImp.findById(EmployeeDAOImp.java:61)
	at com.revature.Driver.main(Driver.java:23)
2019-12-14 12:22:50 WARN  ConnectionUtil:76 - Unable to obtain connection to database
org.postgresql.util.PSQLException: FATAL: database "project0" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2617)
	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:135)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:250)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:74)
	at com.revature.repositories.EmployeeDAOImp.insert(EmployeeDAOImp.java:87)
	at com.revature.Driver.entrySwitch(Driver.java:60)
	at com.revature.Driver.main(Driver.java:18)
2019-12-14 13:41:59 WARN  EmployeeDAOImp:102 - Unable to insert employee.
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "is_unique"
  Detail: Key (login)=(jmoe) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.EmployeeDAOImp.insert(EmployeeDAOImp.java:99)
	at com.revature.services.UserInterface.entrySwitch(UserInterface.java:48)
	at com.revature.Driver.main(Driver.java:8)
2019-12-14 14:29:12 WARN  EmployeeDAOImp:102 - Unable to insert employee.
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "is_unique"
  Detail: Key (login)=(jmoe) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.EmployeeDAOImp.insert(EmployeeDAOImp.java:99)
	at com.revature.services.UserInterface.entrySwitch(UserInterface.java:48)
	at com.revature.Driver.main(Driver.java:8)
2019-12-14 14:37:26 WARN  EmployeeDAOImp:107 - Unable to insert employee.
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "is_unique"
  Detail: Key (login)=(jmoe) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.EmployeeDAOImp.insert(EmployeeDAOImp.java:100)
	at com.revature.services.UserInterface.entrySwitch(UserInterface.java:48)
	at com.revature.Driver.main(Driver.java:8)
2019-12-14 15:20:40 WARN  EmployeeDAOImp:81 - Unable to insert user.
org.postgresql.util.PSQLException: Can't use query methods that take a query string on a PreparedStatement.
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:95)
	at com.revature.repositories.EmployeeDAOImp.findById(EmployeeDAOImp.java:62)
	at com.revature.Driver.main(Driver.java:16)
2019-12-14 15:29:04 WARN  EmployeeDAOImp:80 - Unable to insert user.
org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2786)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1887)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2480)
	at com.revature.repositories.EmployeeDAOImp.findById(EmployeeDAOImp.java:65)
	at com.revature.Driver.main(Driver.java:16)
2019-12-14 20:44:38 WARN  ClientDAOImp:132 - Unable to insert client.
org.postgresql.util.PSQLException: No value specified for parameter 5.
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:264)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:294)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.ClientDAOImp.insert(ClientDAOImp.java:129)
	at com.revature.services.NewUserCreation.newUserAccount(NewUserCreation.java:28)
	at com.revature.services.UserInterface.entrySwitch(UserInterface.java:47)
	at com.revature.Driver.main(Driver.java:9)
2019-12-14 23:33:29 INFO  UserAuthent:39 - Client logged in successfully
2019-12-15 06:10:58 INFO  UserAuthent:39 - Client logged in successfully
2019-12-15 06:22:57 INFO  Driver:13 - Application Started
2019-12-15 06:23:08 INFO  UserAuthent:55 - Client logged in successfully
2019-12-15 12:11:59 INFO  Driver:13 - Application Started
2019-12-15 12:12:11 INFO  UserAuthent:54 - Client logged in successfully
2019-12-15 12:12:32 WARN  ClientDAOImp:157 - Unable to update client.
org.postgresql.util.PSQLException: The column index is out of range: 6, number of columns: 5.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:64)
	at org.postgresql.core.v3.SimpleParameterList.setBinaryParameter(SimpleParameterList.java:131)
	at org.postgresql.jdbc.PgPreparedStatement.bindBytes(PgPreparedStatement.java:1005)
	at org.postgresql.jdbc.PgPreparedStatement.setInt(PgPreparedStatement.java:290)
	at com.revature.repositories.ClientDAOImp.update(ClientDAOImp.java:150)
	at com.revature.services.ClientServices.changeInfo(ClientServices.java:61)
	at com.revature.services.ClientServices.mainMenu(ClientServices.java:27)
	at com.revature.services.UserAuthent.UserConfirm(UserAuthent.java:55)
	at com.revature.services.UserInterface.entrySwitch(UserInterface.java:46)
	at com.revature.Driver.main(Driver.java:14)
2019-12-15 12:12:32 INFO  ClientServices:64 - last name changed
2019-12-15 12:15:44 INFO  Driver:13 - Application Started
2019-12-15 12:15:57 INFO  UserAuthent:36 - Client logged in successfully
2019-12-15 12:16:12 INFO  ClientServices:64 - last name changed
2019-12-15 12:16:24 INFO  ClientServices:30 - User exited from client main menu.
2019-12-15 12:16:49 INFO  Driver:13 - Application Started
2019-12-15 12:17:01 INFO  UserAuthent:54 - Client logged in successfully
2019-12-15 12:17:31 INFO  ClientServices:86 - password changed
2019-12-15 12:18:21 INFO  ClientServices:30 - User exited from client main menu.
2019-12-15 15:17:58 INFO  Driver:13 - Application Started
2019-12-15 15:18:13 INFO  UserAuthent:59 - Client failed user authentification.
2019-12-15 15:18:27 INFO  Driver:13 - Application Started
2019-12-15 15:18:42 INFO  UserAuthent:54 - Client logged in successfully
2019-12-15 15:18:44 WARN  AccountDAOImp:107 - Unable to retrieve all users
org.postgresql.util.PSQLException: ERROR: syntax error at end of input
  Position: 42
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repositories.AccountDAOImp.findByOwnerId(AccountDAOImp.java:91)
	at com.revature.services.AccountServices.manageAccounts(AccountServices.java:18)
	at com.revature.services.ClientServices.mainMenu(ClientServices.java:23)
	at com.revature.services.UserAuthent.UserConfirm(UserAuthent.java:55)
	at com.revature.services.UserInterface.entrySwitch(UserInterface.java:46)
	at com.revature.Driver.main(Driver.java:14)
2019-12-15 15:21:02 INFO  Driver:13 - Application Started
2019-12-15 15:24:38 INFO  UserAuthent:54 - Client logged in successfully
2019-12-15 15:32:45 INFO  Driver:13 - Application Started
2019-12-15 15:32:59 INFO  UserAuthent:54 - Client logged in successfully
2019-12-15 15:33:20 INFO  AccountServices:72 - Deposit made into account
2019-12-15 15:36:02 INFO  Driver:13 - Application Started
2019-12-15 15:36:22 INFO  UserAuthent:54 - Client logged in successfully
2019-12-15 15:36:34 INFO  AccountServices:72 - Deposit made into account
2019-12-15 16:47:56 INFO  Driver:13 - Application Started
2019-12-15 16:48:38 INFO  UserAuthent:54 - Client logged in successfully
2019-12-15 16:49:09 INFO  AccountServices:97 - transfer made between accounts3and2
2019-12-15 21:10:29 INFO  AccountServices:59 - User exited from accounts menu.
2019-12-15 22:18:46 INFO  Driver:13 - Application Started
2019-12-15 22:19:05 INFO  UserAuthent:54 - Client logged in successfully
2019-12-15 22:19:25 INFO  AccountServices:221 - User applied for a new bank account
2019-12-15 22:20:41 INFO  Driver:13 - Application Started
2019-12-15 22:21:00 INFO  UserAuthent:54 - Client logged in successfully
2019-12-15 22:21:16 INFO  AccountServices:59 - User exited from accounts menu.
2019-12-15 22:21:16 INFO  AccountServices:32 - User tried to access an unapproved account.
2019-12-15 23:12:47 INFO  Driver:13 - Application Started
2019-12-15 23:14:16 INFO  UserAuthent:85 - Employee failed user authentification.
2019-12-15 23:21:09 INFO  Driver:13 - Application Started
2019-12-15 23:22:11 INFO  Driver:13 - Application Started
2019-12-15 23:22:27 INFO  UserAuthent:80 - Employee logged in successfully
2019-12-15 23:22:44 INFO  AccountServices:320 - Account 4 approved.
2019-12-15 23:22:58 INFO  Driver:13 - Application Started
2019-12-15 23:23:33 INFO  UserAuthent:98 - Employee logged in successfully
2019-12-15 23:24:08 INFO  Driver:13 - Application Started
2019-12-15 23:24:22 INFO  UserAuthent:141 - Admin logged in successfully
2019-12-15 23:24:28 INFO  Driver:13 - Application Started
2019-12-15 23:24:40 INFO  UserAuthent:98 - Employee logged in successfully
2019-12-15 23:24:46 INFO  EmployeeServices:69 - User looked at account 1.
2019-12-15 23:25:22 INFO  Driver:13 - Application Started
2019-12-15 23:25:39 INFO  UserAuthent:98 - Employee logged in successfully
2019-12-15 23:25:43 INFO  EmployeeServices:45 - User looked at account 2.
2019-12-15 23:25:55 INFO  EmployeeServices:32 - User exited from Employee main menu.
2019-12-16 09:48:38 INFO  Driver:13 - Application Started
2019-12-16 09:48:55 INFO  UserAuthent:141 - Admin logged in successfully
2019-12-16 09:49:32 INFO  AccountServices:97 - transfer made between accounts2and3
2019-12-16 09:50:57 INFO  AccountServices:153 - Deposit made into account
2019-12-16 09:51:29 INFO  AccountServices:59 - User exited from accounts menu.
2019-12-16 09:51:56 INFO  Driver:13 - Application Started
2019-12-16 09:52:15 INFO  UserAuthent:141 - Admin logged in successfully
2019-12-16 09:52:31 INFO  AdminServices:90 - Employee 13 was approved.
2019-12-16 09:55:49 INFO  Driver:13 - Application Started
2019-12-16 09:56:06 INFO  UserAuthent:141 - Admin logged in successfully
2019-12-16 09:56:17 INFO  AdminServices:91 - Employee 13 was approved.
2019-12-16 14:42:16 INFO  AdminServices:43 - User exited from Employee main menu.
2019-12-16 14:50:22 WARN  EmployeeDAOImp:102 - Unable to insert employee.
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "is_unique"
  Detail: Key (login)=(etest) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.EmployeeDAOImp.insert(EmployeeDAOImp.java:99)
	at com.revature.services.NewUserCreation.constructEmployee(NewUserCreation.java:51)
	at com.revature.services.NewUserCreationTest.testConstructEmployeeLastFalse(NewUserCreationTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
2019-12-16 14:50:22 WARN  EmployeeDAOImp:102 - Unable to insert employee.
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "is_unique"
  Detail: Key (login)=(etest) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.EmployeeDAOImp.insert(EmployeeDAOImp.java:99)
	at com.revature.services.NewUserCreation.constructEmployee(NewUserCreation.java:51)
	at com.revature.services.NewUserCreationTest.testConstructEmployeePassFalse(NewUserCreationTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
2019-12-16 14:50:22 WARN  EmployeeDAOImp:102 - Unable to insert employee.
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "is_unique"
  Detail: Key (login)=(etest) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.EmployeeDAOImp.insert(EmployeeDAOImp.java:99)
	at com.revature.services.NewUserCreation.constructEmployee(NewUserCreation.java:51)
	at com.revature.services.NewUserCreationTest.testConstructEmployee(NewUserCreationTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
2019-12-16 14:50:22 WARN  EmployeeDAOImp:102 - Unable to insert employee.
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "is_unique"
  Detail: Key (login)=(etest) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.EmployeeDAOImp.insert(EmployeeDAOImp.java:99)
	at com.revature.services.NewUserCreation.constructEmployee(NewUserCreation.java:51)
	at com.revature.services.NewUserCreationTest.testConstructEmployeeFirstFalse(NewUserCreationTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
2019-12-16 21:03:58 INFO  AccountServices:145 - User tried to withdraw a negative amount
2019-12-16 21:03:59 INFO  AccountServices:140 - Deposit made into account
2019-12-16 21:03:59 INFO  AccountServices:140 - Deposit made into account
2019-12-16 21:03:59 INFO  AccountServices:109 - User tried to transfer a negative amount
2019-12-16 21:03:59 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-16 21:03:59 INFO  AccountServices:176 - Deposit made into account
2019-12-16 21:03:59 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-16 21:03:59 INFO  AccountServices:181 - User tried to deposit a negative amount
2019-12-16 21:03:59 INFO  AccountServices:181 - User tried to deposit a negative amount
2019-12-16 21:03:59 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-16 21:03:59 INFO  AccountServices:145 - User tried to withdraw a negative amount
2019-12-16 21:03:59 INFO  AccountServices:176 - Deposit made into account
2019-12-16 21:03:59 INFO  AccountServices:109 - User tried to transfer a negative amount
2019-12-16 21:03:59 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-16 21:06:21 INFO  AccountServices:145 - User tried to withdraw a negative amount
2019-12-16 21:06:21 INFO  AccountServices:140 - Deposit made into account
2019-12-16 21:06:22 INFO  AccountServices:140 - Deposit made into account
2019-12-16 21:06:22 INFO  AccountServices:109 - User tried to transfer a negative amount
2019-12-16 21:06:22 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-16 21:06:22 INFO  AccountServices:176 - Deposit made into account
2019-12-16 21:06:22 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-16 21:06:22 INFO  AccountServices:181 - User tried to deposit a negative amount
2019-12-16 21:06:22 INFO  AccountServices:181 - User tried to deposit a negative amount
2019-12-16 21:06:22 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-16 21:06:22 INFO  AccountServices:145 - User tried to withdraw a negative amount
2019-12-16 21:06:22 INFO  AccountServices:176 - Deposit made into account
2019-12-16 21:06:22 INFO  AccountServices:109 - User tried to transfer a negative amount
2019-12-16 21:06:22 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-16 21:07:45 INFO  AccountServices:145 - User tried to withdraw a negative amount
2019-12-16 21:07:45 INFO  AccountServices:140 - Deposit made into account
2019-12-16 21:07:45 INFO  AccountServices:140 - Deposit made into account
2019-12-16 21:07:45 INFO  AccountServices:109 - User tried to transfer a negative amount
2019-12-16 21:07:45 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-16 21:07:45 INFO  AccountServices:176 - Deposit made into account
2019-12-16 21:07:45 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-16 21:07:45 INFO  AccountServices:181 - User tried to deposit a negative amount
2019-12-16 21:07:45 INFO  AccountServices:181 - User tried to deposit a negative amount
2019-12-16 21:07:45 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-16 21:07:45 INFO  AccountServices:145 - User tried to withdraw a negative amount
2019-12-16 21:07:45 INFO  AccountServices:176 - Deposit made into account
2019-12-16 21:07:45 INFO  AccountServices:109 - User tried to transfer a negative amount
2019-12-16 21:07:45 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-16 21:51:32 INFO  Driver:108 - Application Started
2019-12-16 21:52:12 INFO  UserInterface:54 - User quit on entry screen.
2019-12-16 21:52:12 WARN  UserInterface:58 - inproper case returned to entry switch statement.
2019-12-16 21:53:07 INFO  Driver:108 - Application Started
2019-12-16 21:55:10 INFO  Driver:108 - Application Started
2019-12-17 07:34:27 INFO  AccountServices:145 - User tried to withdraw a negative amount
2019-12-17 07:34:27 INFO  AccountServices:140 - Deposit made into account
2019-12-17 07:34:27 INFO  AccountServices:140 - Deposit made into account
2019-12-17 07:34:27 INFO  AccountServices:109 - User tried to transfer a negative amount
2019-12-17 07:34:27 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-17 07:34:27 INFO  AccountServices:176 - Deposit made into account
2019-12-17 07:34:27 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-17 07:34:27 INFO  AccountServices:181 - User tried to deposit a negative amount
2019-12-17 07:34:27 INFO  AccountServices:181 - User tried to deposit a negative amount
2019-12-17 07:34:28 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-17 07:34:28 INFO  AccountServices:145 - User tried to withdraw a negative amount
2019-12-17 07:34:28 INFO  AccountServices:176 - Deposit made into account
2019-12-17 07:34:28 INFO  AccountServices:109 - User tried to transfer a negative amount
2019-12-17 07:34:28 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-17 07:34:28 WARN  EmployeeDAOImp:102 - Unable to insert employee.
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "is_unique"
  Detail: Key (login)=(t) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.EmployeeDAOImp.insert(EmployeeDAOImp.java:99)
	at com.revature.services.NewUserCreation.constructEmployee(NewUserCreation.java:51)
	at com.revature.services.NewUserCreationTest.testConstructEmployeeNameFalse(NewUserCreationTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
2019-12-17 07:34:28 WARN  EmployeeDAOImp:102 - Unable to insert employee.
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "is_unique"
  Detail: Key (login)=(etest) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.EmployeeDAOImp.insert(EmployeeDAOImp.java:99)
	at com.revature.services.NewUserCreation.constructEmployee(NewUserCreation.java:51)
	at com.revature.services.NewUserCreationTest.testConstructEmployeeLastFalse(NewUserCreationTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
2019-12-17 07:34:28 WARN  EmployeeDAOImp:102 - Unable to insert employee.
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "is_unique"
  Detail: Key (login)=(etest) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.EmployeeDAOImp.insert(EmployeeDAOImp.java:99)
	at com.revature.services.NewUserCreation.constructEmployee(NewUserCreation.java:51)
	at com.revature.services.NewUserCreationTest.testConstructEmployeePassFalse(NewUserCreationTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
2019-12-17 07:34:28 WARN  EmployeeDAOImp:102 - Unable to insert employee.
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "is_unique"
  Detail: Key (login)=(etest) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.EmployeeDAOImp.insert(EmployeeDAOImp.java:99)
	at com.revature.services.NewUserCreation.constructEmployee(NewUserCreation.java:51)
	at com.revature.services.NewUserCreationTest.testConstructEmployee(NewUserCreationTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
2019-12-17 07:34:28 WARN  EmployeeDAOImp:102 - Unable to insert employee.
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "is_unique"
  Detail: Key (login)=(etest) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.EmployeeDAOImp.insert(EmployeeDAOImp.java:99)
	at com.revature.services.NewUserCreation.constructEmployee(NewUserCreation.java:51)
	at com.revature.services.NewUserCreationTest.testConstructEmployeeFirstFalse(NewUserCreationTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
2019-12-17 07:35:27 INFO  Driver:108 - Application Started
2019-12-17 08:33:45 INFO  Driver:147 - Application Started
2019-12-17 08:34:12 INFO  UserAuthent:59 - Client failed user authentification.
2019-12-17 08:34:20 INFO  Driver:147 - Application Started
2019-12-17 08:34:29 INFO  UserAuthent:54 - Client logged in successfully
2019-12-17 08:55:22 INFO  Driver:147 - Application Started
2019-12-17 08:56:04 INFO  UserAuthent:54 - Client logged in successfully
2019-12-17 08:57:05 INFO  Driver:147 - Application Started
2019-12-17 08:57:19 INFO  UserAuthent:54 - Client logged in successfully
2019-12-17 08:57:22 INFO  AccountServices:37 - User tried to access account they do not own
2019-12-17 09:14:59 INFO  Driver:147 - Application Started
2019-12-17 09:55:29 INFO  AccountServices:145 - User tried to withdraw a negative amount
2019-12-17 09:55:29 INFO  AccountServices:140 - Deposit made into account
2019-12-17 09:55:29 INFO  AccountServices:140 - Deposit made into account
2019-12-17 09:55:29 INFO  AccountServices:109 - User tried to transfer a negative amount
2019-12-17 09:55:29 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-17 09:55:29 INFO  AccountServices:176 - Deposit made into account
2019-12-17 09:55:29 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-17 09:55:29 INFO  AccountServices:181 - User tried to deposit a negative amount
2019-12-17 09:55:29 INFO  AccountServices:181 - User tried to deposit a negative amount
2019-12-17 09:55:30 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-17 09:55:30 INFO  AccountServices:145 - User tried to withdraw a negative amount
2019-12-17 09:55:30 INFO  AccountServices:176 - Deposit made into account
2019-12-17 09:55:30 INFO  AccountServices:109 - User tried to transfer a negative amount
2019-12-17 09:55:30 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-17 10:04:13 INFO  Driver:147 - Application Started
2019-12-17 10:10:23 INFO  Driver:147 - Application Started
2019-12-17 10:18:49 INFO  Driver:147 - Application Started
2019-12-17 10:21:04 INFO  Driver:147 - Application Started
2019-12-17 11:02:17 INFO  ClientServices:86 - password changed
2019-12-17 11:02:17 INFO  ClientServices:86 - password changed
2019-12-17 11:02:17 INFO  ClientServices:116 - first name changed
2019-12-17 11:02:17 INFO  ClientServices:96 - login name changed
2019-12-17 11:02:17 INFO  ClientServices:106 - last name changed
2019-12-17 11:02:18 INFO  ClientServices:106 - last name changed
2019-12-17 11:02:18 INFO  ClientServices:116 - first name changed
2019-12-17 11:02:18 INFO  ClientServices:96 - login name changed
2019-12-17 11:03:36 INFO  ClientServices:86 - password changed
2019-12-17 11:03:36 INFO  ClientServices:86 - password changed
2019-12-17 11:03:36 INFO  ClientServices:116 - first name changed
2019-12-17 11:03:36 INFO  ClientServices:96 - login name changed
2019-12-17 11:03:37 INFO  ClientServices:106 - last name changed
2019-12-17 11:03:37 INFO  ClientServices:106 - last name changed
2019-12-17 11:03:37 INFO  ClientServices:116 - first name changed
2019-12-17 11:03:37 INFO  ClientServices:96 - login name changed
2019-12-17 11:04:07 INFO  AccountServices:145 - User tried to withdraw a negative amount
2019-12-17 11:04:07 INFO  AccountServices:140 - Deposit made into account
2019-12-17 11:04:07 INFO  AccountServices:140 - Deposit made into account
2019-12-17 11:04:07 INFO  AccountServices:109 - User tried to transfer a negative amount
2019-12-17 11:04:08 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-17 11:04:08 INFO  AccountServices:176 - Deposit made into account
2019-12-17 11:04:08 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-17 11:04:08 INFO  AccountServices:181 - User tried to deposit a negative amount
2019-12-17 11:04:08 INFO  AccountServices:181 - User tried to deposit a negative amount
2019-12-17 11:04:08 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-17 11:04:08 INFO  AccountServices:145 - User tried to withdraw a negative amount
2019-12-17 11:04:08 INFO  AccountServices:176 - Deposit made into account
2019-12-17 11:04:08 INFO  AccountServices:109 - User tried to transfer a negative amount
2019-12-17 11:04:08 INFO  AccountServices:105 - transfer made between accounts0and0
2019-12-17 11:04:08 INFO  ClientServices:86 - password changed
2019-12-17 11:04:08 INFO  ClientServices:86 - password changed
2019-12-17 11:04:08 INFO  ClientServices:116 - first name changed
2019-12-17 11:04:08 INFO  ClientServices:96 - login name changed
2019-12-17 11:04:09 INFO  ClientServices:106 - last name changed
2019-12-17 11:04:09 INFO  ClientServices:106 - last name changed
2019-12-17 11:04:09 INFO  ClientServices:116 - first name changed
2019-12-17 11:04:09 INFO  ClientServices:96 - login name changed
